version: 2

project_name: devcontainerwizard

builds:
  - main: .
    id: devcontainerwizard
    binary: devcontainerwizard
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w"

archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files: []

release:
  github:
    owner: lucasassuncao
    name: devcontainerwizard
  draft: false
  prerelease: auto

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"
